### ISSUE TITLE
In Text API the parameter `webhookUrl` works with request body.

### ISSUE THREAD

**Issue by harpreetvishnoi** [symblai/symbl-docs#127]
## Expected content
Text API only supports parameters in the Request Body. 

The `webhookUrl` works with request body. It needs to be moved to the respective section. 

## Actual content
![image](https://user-images.githubusercontent.com/67150433/130597891-e36ca802-7267-4c97-9ec3-0adb9bcc225e.png)

**Link to page**:
https://docs.symbl.ai/docs/async-api/overview/text/post-text

**Comment by pema-s** [comment]
@harpreetvishnoi This has been fixed.
