### ISSUE TITLE
Trackers and Analytics UI

### ISSUE THREAD

**Issue by harpreetvishnoi** [symblai/symbl-docs#14]
## Expected content
Can we add an image and demo URL on top so users can test it out for themselves. 

![image](https://user-images.githubusercontent.com/67150433/121765208-e1c7c300-cb66-11eb-9dca-8d6232298dcd.png)

## Actual content

**Link to page**:

**Comment by pema-s** [comment]
Demo links have been added @harpreetvishnoi 

https://docs.symbl.ai/docs/pre-built-ui/summary-ui
