### ISSUE TITLE
Sample Response has empty responses

### ISSUE THREAD

**Issue by Akankshabhasin** [symblai/symbl-docs#232]
In https://docs.symbl.ai/docs/conversation-api/action-items  sample response, entities are returned as empty throughout. Action Items are our unique feature, and the example should illustrate the full-extent of it or it won’t be clear to new people.

## Expected content/Solution
Replace with an example response that either has all response parameters, or no empty response parameters. 

**Link to page**: https://docs.symbl.ai/docs/conversation-api/action-items

**Comment by howdyAnkit** [comment]
Hey, @Akankshabhasin I'd like to give this a try. let me know If i can get assigned for this :)

**Comment by Akankshabhasin** [comment]
This has been fixed.
