### ISSUE TITLE
Fix: Summarization Endpoint 

### ISSUE THREAD

**Issue by moona3k** [symblai/symbl-docs#234]
## Requested Change
The base url for `Async Video URL API` should be the same as the other endpoints.

<img width="1384" alt="Screen Shot 2021-10-11 at 12 37 33 PM" src="https://user-images.githubusercontent.com/32221114/136846755-fca5f029-7869-41e6-b611-274e43bd8945.png">

**Link to page**: https://docs.symbl.ai/docs/concepts/summarization

**Comment by pema-s** [comment]
This has been fixed by @yres-dev
