### ISSUE TITLE
[Docs Update]: remove `$` from Readme

### ISSUE THREAD

**Issue by shubhangi013** [symblai/symbl-docs#253]
### Contact Details

shubhangi.student.eee20@itbhu.ac.in

### Description

Since the commands are to be copied by the user, using `$` before each one doesn't make sense and for somebody new to using commands can cause errors.

**Comment by shubhangi013** [comment]
> Hi @shubhangi013, I would like to give this a try. If not an issue, you can assign this to me!!!

Hi! I've already opened a PR regarding this. 😅

**Comment by Bikramjit21** [comment]
Is this issue completed or can I try this?

**Comment by prykdev** [comment]
is this still open can i work on this?

**Comment by govind2404** [comment]
@shubhangi013 I would like to work on this issue.

**Comment by shubhangi013** [comment]
Actually I did raise a PR and they said it's not needed. Hence, I'm closing this issue.
