### ISSUE TITLE
[Docs Update]: Rewriting the process of setting up docs locally using HTTPS with detailed steps

### ISSUE THREAD

**Issue by Sproff** [symblai/symbl-docs#255]
### Contact Details

sproff.oluwaseun@gmail.com

### Description

![pr](https://user-images.githubusercontent.com/61986442/137557855-00950b2a-0e8e-4eed-932b-0b5cd8f0f5e2.png)

**Comment by Ln11211** [comment]
@Sproff , can I try doing this ?

**Comment by pema-s** [comment]
@Sproff @appsplash99 @Ln11211 Can you please confirm who is working on this?

**Comment by prykdev** [comment]
Can i work on this?
