### ISSUE TITLE
[Bug]: In https://github.com/symblai/symbl-docs/blob/develop/what-is-symbl.md, in this the links under Symbl’s Key Capabilities are not working like the link of sentiment analysis (eg : https://github.com/symblai/symbl-docs/blob/develop/docs/concepts/speech-to-text)

### ISSUE THREAD

**Issue by VanshajPoonia** [symblai/symbl-docs#272]
### Contact Details

vanshajtheunique@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- OS:
- Node:
- npm:
```

**Comment by pema-s** [comment]
Hi @VanshajPoonia 
The links within GitHub pages will not work in the same way as it does when it is rendered in the HTML file. Our docs linking uses an internal repository structure so the same will not work when hosted on GH.
