### ISSUE TITLE
 Dark Theme is not working in some section

### ISSUE THREAD

**Issue by madhhuurrii** [symblai/symbl-docs#302]
### Contact Details

madhuriramakrishnan19@siesgst.ac.in

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Dark Mode Theme is not working properly in some section, which causes difficulty in reading some text.
![image](https://user-images.githubusercontent.com/64744084/145273786-df89cc78-ac38-4ba4-b0bc-ac7416af6ebf.png)

### Environment

```markdown
- OS: Windows 10
- Node:
- npm:
```

### What browsers are you seeing the problem on?

Chrome

**Comment by pema-s** [comment]
Hi @madhhuurrii Thanks for reporting this. We changed the color of the box to fix this.
