### ISSUE TITLE
[Docs Update]: Not able to run the project on local

### ISSUE THREAD

**Issue by RiyaGupta89** [symblai/symbl-docs#307]
### Contact Details

riyag0841@gmail.com

### Description

I followed the documentation i.e. cloned the repo and cd into the directory and then ran yarn for installing all of the packages and then yarn start for running the project on local but there's no package.json file present. I guess, i have to cd further into any directory and then do yarn start.
Please help and then correct the documentation as well.

**Comment by pema-s** [comment]
Hi @RiyaGupta89 Yes, currently building the docs locally has an issue and we are working on it. The best way to contribute is to use the button "Edit this page" available in our docs and submit it via GitHub.
