### ISSUE TITLE
Response is missing for Telephony API Code Snippets

### ISSUE THREAD

**Issue by harpreetvishnoi** [symblai/symbl-docs#68]
## Actual content

**Link to page**:

https://docs.symbl.ai/docs/telephony/

**Comment by pema-s** [comment]
@harpreetvishnoi Can you share the right link to the doc where the sample is missing?

**Comment by harpreetvishnoi** [comment]
Hey @pema-s if you see in the entire telephony code snippet and tutorial section there is no mention of its response. It's not a blocker but a good one to have.

**Comment by pema-s** [comment]
@harpreetvishnoi Working on this one.

**Comment by pema-s** [comment]
As discussed, added response samples in the following pages:

- https://docs.symbl.ai/docs/telephony/code-snippets/connect-to-pstn
- https://docs.symbl.ai/docs/telephony/code-snippets/connect-to-sip
- https://docs.symbl.ai/docs/telephony/code-snippets/receive-speech-to-text-for-a-different-language
- https://docs.symbl.ai/docs/telephony/code-snippets/receive-prebuilt-ui-email-after-conversation

For Telephony API with JS SDK, we will first standardize the format and then add.

**Comment by pemasp** [comment]
This has been fixed. Issue can be closedd
