### ISSUE TITLE
Readability for Trackers API Async Request 

### ISSUE THREAD

**Issue by harpreetvishnoi** [symblai/symbl-docs#69]
## Expected content
`https: //api.symbl.ai/v1/process/audio?trackers=[
  {
    "name": "COVID-19",
    "vocabulary": [
      "social distancing",
      "cover your face with mask",
      "vaccination"
    ]
  }
]`

## Actual content
![image](https://user-images.githubusercontent.com/67150433/124764155-4a317680-df52-11eb-81cc-12f3ece8e90e.png)

https://api.symbl.ai/v1/process/audio?trackers=[{"name":"COVID-19", "vocabulary":["social distancing", "cover your face with mask", "vaccination"]}]

**Link to page**:

**Comment by pema-s** [comment]
Hi @harpreetvishnoi 

What is the change you are proposing? Is it to remove the black code box for the API endpoint? 

Please confirm

**Comment by harpreetvishnoi** [comment]
Hi @pema-s 
Readability for Trackers API Request needs to be improved. It should be in JSON formated structure mentioned below. 
Having the entire tracker in a single line is hard to read. 

PS: Sorry for the delay in reply. I didn't get an email notification for this

https: //api.symbl.ai/v1/process/audio?trackers=[
  {
    "name": "COVID-19",
    "vocabulary": [
      "social distancing",
      "cover your face with mask",
      "vaccination"
    ]
  }
]

**Comment by pema-s** [comment]
@harpreetvishnoi Since this is passed as a query parameter, the sample is shown that way on purpose.

**Comment by harpreetvishnoi** [comment]
Hi @pema-s 

The tracker's Request is not in JSON format that is the issue. The entire request being in a single line reduces how the user reads it. 

It should be in JSON format. 

Current Format: 
`https://api.symbl.ai/v1/process/audio?trackers=[{"name":"COVID-19", "vocabulary":["social distancing", "cover your face with mask", "vaccination"]}]`

Ideal Format:

`https: //api.symbl.ai/v1/process/audio?trackers=[
  {
    "name": "COVID-19",
    "vocabulary": [
      "social distancing",
      "cover your face with mask",
      "vaccination"
    ]
  }
]`

**Comment by pema-s** [comment]
@harpreetvishnoi The format of the sample has been updated.
